"Cap_tripulacion" 1
"Cap_pasajero"2
"Dist_Asiento"3 -> 76
"Longitud"4
"Envergadura"5
"Altura"6
"Flecha_alar"7 ->25.04
"Ancho_fuselaje"8 -> 3.76
"Alto_fuselaje"9 -> 4.01
"Ancho_cabina"10 -> 3.54
"Alto_cabina"11 -> 2.20
"Peso_vacio"12
"Peso_max_despegue"13
"Peso_max_aterrizaje"14 -> 23500
"Velocidad_crucero"15
"Velocidad_max"16
"Alcance_carga_max"17 -> 3700
"Capacidad_max_combustible"18
"Motor"19
"Empuje_max"20
"Empuje_normal"21
"Longitud_motor"22 -> 2.5