insert into tipo_pieza (tp_nombre) values ('Alas');
insert into tipo_pieza (tp_nombre) values ('Fuselaje');
insert into tipo_pieza (tp_nombre) values ('Timón de dirección');
insert into tipo_pieza (tp_nombre) values ('Timón de profundidad');
insert into tipo_pieza (tp_nombre) values ('Tren de aterrizaje');
insert into tipo_pieza (tp_nombre) values ('Motor');
insert into tipo_pieza (tp_nombre) values ('Hélice');
insert into tipo_pieza (tp_nombre) values ('Flaps');
insert into tipo_pieza (tp_nombre) values ('Alerones');
insert into tipo_pieza (tp_nombre) values ('Estabilizador horizontal');
insert into tipo_pieza (tp_nombre) values ('Estabilizador vertical');
insert into tipo_pieza (tp_nombre) values ('Cabina');
insert into tipo_pieza (tp_nombre) values ('Ventanas');
insert into tipo_pieza (tp_nombre) values ('Puertas');
insert into tipo_pieza (tp_nombre) values ('Tanque de combustible');
insert into tipo_pieza (tp_nombre) values ('Sistema de navegación');
insert into tipo_pieza (tp_nombre) values ('Sistema de comunicación');
insert into tipo_pieza (tp_nombre) values ('Sistema hidráulico');
insert into tipo_pieza (tp_nombre) values ('Sistema eléctrico');
insert into tipo_pieza (tp_nombre) values ('Sistema de control de vuelo');