insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a las Alas del avión.', '2021-01-01', 1, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Fuselaje del avión.', '2020-05-15', 2, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Timón de dirección del avión.', '2019-08-20', 3, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Timón de profundidad del avión.', '2018-11-30', 4, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Tren de aterrizaje del avión.', '2017-03-10', 5, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Motor del avión.', '2016-07-25', 6, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a la Hélice del avión.', '2015-12-05', 7, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a los Flaps del avión.', '2014-04-18', 8, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a los Alerones del avión.', '2022-09-12', 9, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Estabilizador horizontal del avión.', '2023-02-22', 10, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Estabilizador vertical del avión.', '2024-06-30', 11, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a la Cabina del avión.', '2019-01-14', 12, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a las Ventanas del avión.', '2018-10-10', 13, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente a las Puertas del avión.', '2017-05-05', 14, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Tanque de combustible del avión.', '2016-08-08', 15, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Sistema de navegación del avión.', '2015-11-11', 16, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Sistema de comunicación del avión.', '2014-02-02', 17, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Sistema hidráulico del avión.', '2021-03-03', 18, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Sistema eléctrico del avión.', '2020-04-04', 19, 20);
insert into pieza (pie_descripcion, pie_fecha_in, fk_tpieza, pie_cantidad) values ('Pieza correspondiente al Sistema de control de vuelo del avión.', '2019-05-05', 20, 20);