insert into tipo_maquinaria (tipo_maq_nombre) values ('Maquinaria para mantenimiento');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Tornos');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Máquinas de corte por láser');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Robots industriales');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Autoclaves');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Grúas');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Plataformas elevadoras');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Taladros');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Equipos de inspección');
insert into tipo_maquinaria (tipo_maq_nombre) values ('Pistolas de remachado');