insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Maquinaria utilizada para el mantenimiento general de equipos y sistemas.', 1);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Tornos utilizados para dar forma a materiales mediante rotación.', 2);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Máquinas de corte que utilizan láser para realizar cortes precisos.', 3);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Robots industriales empleados en procesos automatizados de manufactura.', 4);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Autoclaves utilizados para la esterilización mediante vapor a alta presión.', 5);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Grúas utilizadas para levantar y mover cargas pesadas.', 6);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Plataformas elevadoras para trabajos en altura de manera segura.', 7);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Taladros utilizados para perforar materiales como metal, madera y plástico.', 8);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Equipos de inspección para verificar la calidad y precisión de los productos.', 9);
insert into maquinaria (maq_descripcion, "fk_Tmaquina") values ('Pistolas de remachado utilizadas para unir piezas mediante remaches.', 10);