insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('sistemas de aviónica', 42);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('fatiga', 22);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('vibración', 13);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('vibración', 10);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('fatiga', 20);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('ruido', 4);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('sistemas', 12);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('rendimiento', 23);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('sistemas de aviónica', 7);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('vibración', 13);
