insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Ingeniero aeronautico','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Tecnico de Diseno','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Mecanico de aeronave','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Ensamblador de estructuras','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Tecnico de aviacion','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Gerente de proyecto','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Personal de prueba','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Logistica','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Ingeniero metalurgico','3');
insert into public."cargo" ("car_cod", "car_nombre", "car_sueldo_hora_extra") values (nextval('car_cod_seq'), 'Ingeniero mecanico','3');