insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba sistemas de aviónica', 42);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba fatiga', 22);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba vibración', 13);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba vibración', 10);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba fatiga', 20);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba ruido', 4);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba sistemas', 12);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba rendimiento', 23);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba sistemas de aviónica', 7);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba vibración', 13);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de motor', 35);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de aterrizaje', 28);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de despegue', 45);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de vuelo', 38);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas eléctricos', 25);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de combustible', 19);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de presurización', 41);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de frenos', 30);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de radar', 27);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de comunicación', 33);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de navegación', 22);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de altitud', 36);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de velocidad', 29);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de estabilidad', 40);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de control', 31);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de cabina', 26);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de oxígeno', 18);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de emergencia', 34);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de evacuación', 21);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de iluminación', 24);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de climatización', 32);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de hidráulicos', 37);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de tren de aterrizaje', 39);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de control', 20);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de navegación', 23);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de comunicación', 17);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de radar', 42);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de frenos', 15);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas de combustible', 14);
insert into tipo_prueba (tprueba_nombre, tprueba_duracion_estim) values ('prueba de sistemas eléctricos', 13);
