CREATE SEQUENCE pru_cod_seq START WITH 1 INCREMENT BY 1;

insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),4);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),3);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),2);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),1);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),1);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),7);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),5);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),4);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),2);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),8);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),9);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),2);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),2);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),1);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),5);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),6);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),7);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),4);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),5);
insert into public."prueba" ("pru_cod","fk_tipoPrueba") values (nextval('pru_cod_seq'),9);