insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Aleacion de Aluminio', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Aleacion de Titanio', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Acero Inoxidable', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Compuesto de fibra de carbono', 'Mts2');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Plastico', 'Mts2');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Textil', 'Mts2');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Cuero', 'Mts2');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Aleacion de Magnesio', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Cobre', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Aluminio', 'Ton');
insert into Tipo_Material ("tipo_mat_nombre", "tipo_mat_unidad_medida") values ('Titanio Grado 5', 'Kg');